// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9XkQOzTkE3AUCdGFmPUHwAPuB8hUKZEY',
    appId: '1:615691317345:web:7f004bd20cde43e8fcfa20',
    messagingSenderId: '615691317345',
    projectId: 'tugas-mandiri-fdee0',
    authDomain: 'tugas-mandiri-fdee0.firebaseapp.com',
    databaseURL: 'https://tugas-mandiri-fdee0-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-mandiri-fdee0.firebasestorage.app',
    measurementId: 'G-Z70ZEHR5VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_jcnGVrOztB-0e5RsJxeeAJfhCZpAQE',
    appId: '1:615691317345:android:74d8a36d5d3cdd40fcfa20',
    messagingSenderId: '615691317345',
    projectId: 'tugas-mandiri-fdee0',
    databaseURL: 'https://tugas-mandiri-fdee0-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-mandiri-fdee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBegp2VZ7iFOtNzJxu3KXepV3n7JWgMM10',
    appId: '1:615691317345:ios:9c15930af8f276e3fcfa20',
    messagingSenderId: '615691317345',
    projectId: 'tugas-mandiri-fdee0',
    databaseURL: 'https://tugas-mandiri-fdee0-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-mandiri-fdee0.firebasestorage.app',
    iosBundleId: 'com.example.projekTugasMandiri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBegp2VZ7iFOtNzJxu3KXepV3n7JWgMM10',
    appId: '1:615691317345:ios:9c15930af8f276e3fcfa20',
    messagingSenderId: '615691317345',
    projectId: 'tugas-mandiri-fdee0',
    databaseURL: 'https://tugas-mandiri-fdee0-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-mandiri-fdee0.firebasestorage.app',
    iosBundleId: 'com.example.projekTugasMandiri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9XkQOzTkE3AUCdGFmPUHwAPuB8hUKZEY',
    appId: '1:615691317345:web:f78f30096b37beb7fcfa20',
    messagingSenderId: '615691317345',
    projectId: 'tugas-mandiri-fdee0',
    authDomain: 'tugas-mandiri-fdee0.firebaseapp.com',
    databaseURL: 'https://tugas-mandiri-fdee0-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-mandiri-fdee0.firebasestorage.app',
    measurementId: 'G-N8Q9Z8DPZ0',
  );
}
